server:
  port: 9527


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#            uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-paymen-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2020-10-08T22:21:49.166+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: http://lb://cloud-paymen-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由

